-- 01_create_oltp.sql
CREATE TABLE IF NOT EXISTS "customer" (
  "id" SERIAL PRIMARY KEY,
  "full_name" varchar(255),
  "email" varchar(255) UNIQUE,
  "phone_number" varchar(15),
  "registered_at" timestamptz,
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" SERIAL PRIMARY KEY,
  "category_name" varchar(255),
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "product" (
  "id" SERIAL PRIMARY KEY,
  "name_product" varchar(255),
  "category_id" int NOT NULL,
  "price" numeric(10, 2),
  "quantity" int,
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "orders" (
  "id" SERIAL PRIMARY KEY,
  "customer_id" int NOT NULL,
  "order_date" timestamptz,
  "status" int NOT NULL,
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "order_item" (
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int,
  "discount" numeric(10, 2),
  "gross_amount" numeric(10, 2),
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "payment_date" timestamptz,
  "amount" numeric(10, 2),
  "method" varchar(255),
  "status_id" int NOT NULL,
  "update_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "order_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status_name" varchar(255)
);

ALTER TABLE "product" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("status_id") REFERENCES "order_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("status") REFERENCES "order_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer" ADD CONSTRAINT "email_unique" UNIQUE ("email");

ALTER TABLE "orders" ADD CONSTRAINT "order_date_check" CHECK ("order_date" <= NOW());

ALTER TABLE "payments" ADD CONSTRAINT "amount_check" CHECK ("amount" >= 0);

ALTER TABLE "order_item" ADD CONSTRAINT "quantity_check" CHECK ("quantity" >= 0);